In [18]:
from nsepy import *
from datetime import date
#import matplotlib as plt

In [3]:
data = get_history(symbol="SBIN", start=date(2010,1,1), end=date(2021,12,31))

In [7]:
data.head()

,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
Date,,,,,,,,,,,,,,
2010-01-04,SBIN,EQ,2269.00,2275.0,2300.0,2275.0,2294.0,2291.20,2291.26,1103147,2.527599e+14,NaN,313202,0.2839
2010-01-05,SBIN,EQ,2291.20,2308.0,2310.0,2280.1,2294.0,2292.05,2292.78,1161374,2.662776e+14,NaN,522468,0.4499
2010-01-06,SBIN,EQ,2292.05,2297.0,2315.0,2285.0,2300.0,2305.80,2301.72,1452793,3.343920e+14,NaN,577097,0.3972
2010-01-07,SBIN,EQ,2305.80,2306.0,2310.0,2281.1,2292.0,2292.90,2291.86,857651,1.965618e+14,NaN,333190,0.3885
2010-01-08,SBIN,EQ,2292.90,2294.0,2303.9,2280.1,2287.7,2286.05,2289.08,1045382,2.392961e+14,NaN,535343,0.5121

In [7]:
data.to_csv("SBIN_2010_to_2021.csv")

Old data

In [25]:
data_2001 = get_history(symbol="SBIN", start=date(2001,1,1), end=date(2001,12,31))

In [26]:
data_2022_Nov = get_history(symbol="SBIN", start=date(2022,10,1), end=date(2022,11,11))

In [27]:
data_2022_Nov

,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
Date,,,,,,,,,,,,,,
2022-10-03,SBIN,EQ,530.60,527.60,531.65,518.50,518.95,519.75,525.01,9351162,4.909456e+14,141130,3430661,0.3669
2022-10-04,SBIN,EQ,519.75,533.00,535.80,527.80,532.95,532.70,532.39,8745887,4.656245e+14,128142,3456189,0.3952
2022-10-06,SBIN,EQ,532.70,534.60,541.80,534.60,537.35,537.30,538.44,9507322,5.119102e+14,183101,4430981,0.4661
2022-10-07,SBIN,EQ,537.30,535.50,535.60,526.55,531.00,530.20,529.64,11065307,5.860624e+14,185698,5018194,0.4535
2022-10-10,SBIN,EQ,530.20,525.70,533.90,522.20,531.40,530.75,528.13,9649292,5.096053e+14,191653,3588945,0.3719
2022-10-11,SBIN,EQ,530.75,530.75,533.70,525.50,527.00,527.40,529.35,10825440,5.730463e+14,159970,4518524,0.4174
2022-10-12,SBIN,EQ,527.40,530.00,535.00,526.00,535.00,533.80,530.03,8522604,4.517236e+14,121592,3016240,0.3539
2022-10-13,SBIN,EQ,533.80,533.00,533.80,520.20,521.90,521.45,525.44,12972765,6.816438e+14,166849,6496472,0.5008
2022-10-14,SBIN,EQ,521.45,530.20,534.85,526.00,527.80,527.20,530.03,8545479,4.529375e+14,144578,2924078,0.3422
2022-10-17,SBIN,EQ,527.20,526.40,544.70,524.20,543.20,543.65,538.70,13485349,7.264516e+14,208408,3700920,0.2744
2022-10-18,SBIN,EQ,543.65,547.10,563.50,546.75,562.40,562.45,558.19,20440781,1.140979e+15,245391,9747060,0.4768
2022-10-19,SBIN,EQ,562.45,563.00,563.45,551.55,553.75,553.40,555.40,9540583,5.298845e+14,137573,3398721,0.3562
2022-10-20,SBIN,EQ,553.40,552.00,556.80,545.30,555.50,555.40,551.98,11225588,6.196329e+14,134915,4079003,0.3634
2022-10-21,SBIN,EQ,555.40,557.25,565.80,557.25,561.65,560.85,562.70,11767639,6.621648e+14,198859,4151059,0.3964
2022-10-24,SBIN,EQ,560.85,567.00,572.50,565.90,572.15,570.50,569.46,3692065,2.102465e+14,63147,1510943,0.4092
2022-10-25,SBIN,EQ,570.50,572.50,586.20,568.00,577.00,578.55,578.28,19899324,1.150743e+15,215376,8833736,0.4439
2022-10-27,SBIN,EQ,578.55,583.95,585.00,577.60,579.10,579.65,580.71,13613533,7.905525e+14,209377,5998675,0.4406
2022-10-28,SBIN,EQ,579.65,579.95,582.65,567.00,571.80,570.75,572.65,10043644,5.751516e+14,144061,3054910,0.4319
2022-10-31,SBIN,EQ,570.75,574.95,577.45,568.40,573.50,573.80,572.79,9894639,5.667560e+14,139535,3759140,0.3799
2022-11-01,SBIN,EQ,573.80,576.35,585.75,574.60,576.00,576.90,579.85,12069579,6.998554e+14,163499,5057539,0.4190
2022-11-02,SBIN,EQ,576.90,575.90,578.95,569.90,573.00,573.85,574.79,10241440,5.886695e+14,142730,3773099,0.3684
2022-11-03,SBIN,EQ,573.85,569.00,587.95,568.00,584.15,584.90,581.58,17557998,1.021139e+15,244825,5121059,0.2917
2022-11-04,SBIN,EQ,584.90,586.00,596.95,580.40,595.70,593.95,587.64,25759031,1.513705e+15,302456,10018968,0.3889
2022-11-07,SBIN,EQ,593.95,613.00,622.70,607.70,613.80,614.15,615.56,44265903,2.724845e+15,470162,16413804,0.3708
2022-11-09,SBIN,EQ,614.15,621.00,621.00,610.55,614.60,615.55,615.08,18939854,1.164952e+15,302328,9373877,0.4949
2022-11-10,SBIN,EQ,615.55,613.10,615.10,602.20,605.05,605.75,607.23,11618405,7.055031e+14,232699,4437252,0.3819
2022-11-11,SBIN,EQ,605.75,617.25,619.55,598.50,600.00,601.30,605.28,15525267,9.397104e+14,220631,5651310,0.3640

In [22]:
data_2001.head()

,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
Date,,,,,,,,,,,,,,
2001-01-01,SBIN,EQ,192.65,193.55,197.80,191.10,195.65,195.00,195.28,1060252,2.070511e+13,NaN,NaN,NaN
2001-01-02,SBIN,EQ,195.00,197.60,209.00,195.15,209.00,205.80,202.15,2016036,4.075442e+13,NaN,NaN,NaN
2001-01-03,SBIN,EQ,205.80,206.00,220.45,205.10,216.50,217.30,214.19,5582579,1.195745e+14,NaN,NaN,NaN
2001-01-04,SBIN,EQ,217.30,218.40,221.00,209.25,213.70,212.65,214.36,2779351,5.957702e+13,NaN,NaN,NaN
2001-01-05,SBIN,EQ,212.65,212.70,218.40,210.65,214.00,214.95,215.22,2795495,6.016447e+13,NaN,NaN,NaN

List of securities / scrips traded at NSE

In [32]:
from nsepy.symbols import *
scrip_list = get_symbol_list()
len(scrip_list)

1836

Index constituents

In [42]:
nifty50 = get_index_constituents_list("nifty")
nifty50

,Company Name,Industry,Symbol,Series,ISIN Code
0,ACC Ltd.,CEMENT & CEMENT PRODUCTS,ACC,EQ,INE012A01025
1,Adani Ports and Special Economic Zone Ltd.,SERVICES,ADANIPORTS,EQ,INE742F01042
2,Ambuja Cements Ltd.,CEMENT & CEMENT PRODUCTS,AMBUJACEM,EQ,INE079A01024
3,Asian Paints Ltd.,CONSUMER GOODS,ASIANPAINT,EQ,INE021A01026
4,Axis Bank Ltd.,FINANCIAL SERVICES,AXISBANK,EQ,INE238A01034
5,Bajaj Auto Ltd.,AUTOMOBILE,BAJAJ-AUTO,EQ,INE917I01010
6,Bank of Baroda,FINANCIAL SERVICES,BANKBARODA,EQ,INE028A01039
7,Bharat Heavy Electricals Ltd.,INDUSTRIAL MANUFACTURING,BHEL,EQ,INE257A01026
8,Bharat Petroleum Corporation Ltd.,ENERGY,BPCL,EQ,INE029A01011
9,Bharti Airtel Ltd.,TELECOM,BHARTIARTL,EQ,INE397D01024
10,Bosch Ltd.,AUTOMOBILE,BOSCHLTD,EQ,INE323A01026
11,Cairn India Ltd.,ENERGY,CAIRN,EQ,INE910H01017
12,Cipla Ltd.,PHARMA,CIPLA,EQ,INE059A01026
13,Coal India Ltd.,METALS,COALINDIA,EQ,INE522F01014
14,Dr. Reddy's Laboratories Ltd.,PHARMA,DRREDDY,EQ,INE089A01023
15,GAIL (India) Ltd.,ENERGY,GAIL,EQ,INE129A01019
16,Grasim Industries Ltd.,CEMENT & CEMENT PRODUCTS,GRASIM,EQ,INE047A01013
17,HCL Technologies Ltd.,IT,HCLTECH,EQ,INE860A01027
18,HDFC Bank Ltd.,FINANCIAL SERVICES,HDFCBANK,EQ,INE040A01026
19,Hero MotoCorp Ltd.,AUTOMOBILE,HEROMOTOCO,EQ,INE158A01026
20,Hindalco Industries Ltd.,METALS,HINDALCO,EQ,INE038A01020
21,Hindustan Unilever Ltd.,CONSUMER GOODS,HINDUNILVR,EQ,INE030A01027
22,Housing Development Finance Corporation Ltd.,FINANCIAL SERVICES,HDFC,EQ,INE001A01036
23,I T C Ltd.,CONSUMER GOODS,ITC,EQ,INE154A01025
24,ICICI Bank Ltd.,FINANCIAL SERVICES,ICICIBANK,EQ,INE090A01021
25,Idea Cellular Ltd.,TELECOM,IDEA,EQ,INE669E01016
26,IndusInd Bank Ltd.,FINANCIAL SERVICES,INDUSINDBK,EQ,INE095A01012
27,Infosys Ltd.,IT,INFY,EQ,INE009A01021
28,Kotak Mahindra Bank Ltd.,FINANCIAL SERVICES,KOTAKBANK,EQ,INE237A01028
29,Larsen & Toubro Ltd.,CONSTRUCTION,LT,EQ,INE018A01030
30,Lupin Ltd.,PHARMA,LUPIN,EQ,INE326A01037
31,Mahindra & Mahindra Ltd.,AUTOMOBILE,M&M,EQ,INE101A01026
32,Maruti Suzuki India Ltd.,AUTOMOBILE,MARUTI,EQ,INE585B01010
33,NTPC Ltd.,ENERGY,NTPC,EQ,INE733E01010
34,Oil & Natural Gas Corporation Ltd.,ENERGY,ONGC,EQ,INE213A01029
35,Power Grid Corporation of India Ltd.,ENERGY,POWERGRID,EQ,INE752E01010
36,Punjab National Bank,FINANCIAL SERVICES,PNB,EQ,INE160A01022
37,Reliance Industries Ltd.,ENERGY,RELIANCE,EQ,INE002A01018
38,State Bank of India,FINANCIAL SERVICES,SBIN,EQ,INE062A01020
39,Sun Pharmaceutical Industries Ltd.,PHARMA,SUNPHARMA,EQ,INE044A01036
40,Tata Consultancy Services Ltd.,IT,TCS,EQ,INE467B01029
41,Tata Motors Ltd.,AUTOMOBILE,TATAMOTORS,EQ,INE155A01022
42,Tata Power Co. Ltd.,ENERGY,TATAPOWER,EQ,INE245A01021
43,Tata Steel Ltd.,METALS,TATASTEEL,EQ,INE081A01012
44,Tech Mahindra Ltd.,IT,TECHM,EQ,INE669C01036
45,UltraTech Cement Ltd.,CEMENT & CEMENT PRODUCTS,ULTRACEMCO,EQ,INE481G01011
46,Vedanta Ltd.,METALS,VEDL,EQ,INE205A01025
47,Wipro Ltd.,IT,WIPRO,EQ,INE075A01022
48,Yes Bank Ltd.,FINANCIAL SERVICES,YESBANK,EQ,INE528G01019
49,Zee Entertainment Enterprises Ltd.,MEDIA & ENTERTAINMENT,ZEEL,EQ,INE256A01028

Indices and their EOD data, date wise

In [41]:
from nsepy.history import *
dt = date(2022,11,11)
indices_eod = get_indices_price_list(dt)
indices_eod

,NAME,TIMESTAMP,OPEN,HIGH,LOW,CLOSE,CHANGE,CHANGEPCT,TOTTRDQTY,TOTTRDVAL,PE,PB,DIVYIELD
0,Nifty 50,11-11-2022,18272.35,18362.3,18259.35,18349.70,321.50,1.78,378469072,30732.11,21.92,4.31,1.24
1,Nifty Next 50,11-11-2022,43224.2,43329.25,43033.75,43189.00,410.90,.96,627449548,11323.39,23.15,4.72,1.81
2,Nifty 100,11-11-2022,18505.95,18586.15,18498.9,18573.35,306.25,1.68,1005918620,42055.5,22.63,4.46,1.28
3,Nifty 200,11-11-2022,9675.5,9700.2,9668.5,9693.10,140.70,1.47,1733130284,55886.89,22.73,4.19,1.27
4,Nifty 500,11-11-2022,15633.5,15662.05,15612.45,15649.10,209.10,1.35,2301538901,65405.72,22.77,4.12,1.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,Nifty Composite G-sec Index,11-11-2022,2380.95,2395.55,2380.95,2389.57,9.07,.38,-,-,-,-,-
100,Nifty 10 yr Benchmark G-Sec,11-11-2022,2044.23,2059.37,2044.23,2050.52,6.69,.33,-,-,-,-,-
101,Nifty 10 yr Benchmark G-Sec (Clean Price),11-11-2022,863.63,870.13,863.63,866.33,2.70,.31,-,-,-,-,-
102,Nifty 1D Rate Index,11-11-2022,-,-,-,2065.32,0.32,.02,-,-,-,-,-
103,Nifty50 USD,11-11-2022,-,-,-,7868.05,231.64,3.03,-,-,-,-,-